# services:

#   mongodb:
#     image: mongo:7
#     container_name: crm-mongodb
#     restart: unless-stopped
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db

#     redis:
#     image: redis:7-alpine
#     container_name: crm-redis
#     restart: unless-stopped
#     ports:
#       - "6379:6379"

#   server:
#     build:
#       context: ./server
#     container_name: crm-server
#     restart: unless-stopped
#     ports:
#       - "5000:5000"
#     environment:
#       PORT: 5000
#       MONGO_URI: mongodb://mongodb:27017/CRM
#       JWT_SECRET: my_super_secret_crm_key_2026
#     depends_on:
#       - mongodb

#   client:
#     build:
#       context: ./client
#     container_name: crm-client
#     restart: unless-stopped
#     ports:
#       - "3000:3000"
#     depends_on:
#       - server

# volumes:
#   mongodb_data:


services:

  mongodb:
    image: mongo:7
    container_name: crm-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: crm-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: crm-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/CRM
      REDIS_URL: redis://redis:6379
      JWT_SECRET: crm_2026_f5b580f5de86c527deae9a2dcd52dbfa52e0440e26883d14cf00321982bd116f
    depends_on:
      - mongodb
      - redis

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: crm-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  mongodb_data: